import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: 'TodoNext | CreateNewCase',
    description: 'Generated by create next app',
}

export default function CreateNewCasePage () {
  return (
    <div>
        <h1>Create New Case</h1>
    </div>
  )
}
