import initTranslations from '@/app/i18n';
import CreateNewCase from '@/widgets/CreateNewCase/CreateNewCase';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'TodoNext | CreateNewCase',
    description: 'Generated by create next app',
}

const i18nNamespaces = ['new']

export default async function CreateNewCasePage ({ params: { locale } }: { params: { locale: string }}) {

  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <div>
        <h1>{t('newTitle')}</h1>
        <CreateNewCase/>
    </div>
  )
}
