import CasesList from "@/widgets/CasesList/CasesList"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'TodoNext | MainPage',
  description: 'Generated by create next app',
}


export default function Homepage() {
  return (
    <>
      <h1>TodoList of user Ilya Yudenkov</h1>
      <CasesList/>
    </>
    
  )
}