import CasesList from "@/widgets/CasesList/ui/CasesList"
import { Metadata } from "next"
import { getCases } from "./lib/getCases";
import initTranslations from "@/app/i18n";



export const metadata: Metadata = {
  title: 'TodoNext | CasesPage',
  description: 'Generated by create next app',
}


const i18nNamespaces = ['cases'];


export default async function CasesPage({ params: { locale } }: { params: { locale: string } }) {

  const { t, resources } = await initTranslations(locale, i18nNamespaces);


  const cases = await getCases();

  return (
    <>
      <h1>{t('mainTitle')}</h1>
      <CasesList casesList={cases ? cases : []}/>
    </>
    
  )
}