'use client'

import CasesList from "@/widgets/CasesList/ui/CasesList"
import { Metadata } from "next"
import { getCases } from "./lib/getCases";
import { useTranslations } from "next-intl";
import { T } from "@/shared/lib/TranslateText/ui/T";
import { useEffect, useState } from "react";

type Props = {
  params: {locale: string};
};


// export const metadata: Metadata = {
//   title: 'TodoNext | CasesPage',
//   description: 'Generated by create next app',
// }

interface IText{
  text: string
}

export default function CasesPage({params: {locale}}: Props) {

  const [todos, setTodos] = useState<IText[]>([])
  
useEffect(() => {
  fetch('http://localhost:3001/text')
  .then(res => res.json())
  .then(data => setTodos(data))

},[])
  // const t = useTranslations('CasesPage')



  // const cases = await getCases();

  return (
    <div>
      <h1><T>Главная </T></h1>
      {/* <CasesList casesList={cases ? cases : []}/> */}
      {todos.map(it => (
        <div key={it.text}>
          <p>
            <T>
            {it.text}
            </T></p>
        </div>
      ))}
    </div>
    
  )
}