import CasesList from "@/widgets/CasesList/ui/CasesList"
import { Metadata } from "next"
import { getCases } from "./lib/getCases";
import { useTranslations } from "next-intl";

type Props = {
  params: {locale: string};
};


export const metadata: Metadata = {
  title: 'TodoNext | CasesPage',
  description: 'Generated by create next app',
}


export default  function CasesPage({params: {locale}}: Props) {
  

  const t = useTranslations('CasesPage')

  // const cases = await getCases();

  return (
    <div>
      <h1>{t('mainTitle')}</h1>
      {/* <CasesList casesList={cases ? cases : []}/> */}
    </div>
    
  )
}