import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cl from '@/shared/styles/_global.module.scss'
import Header from '@/widgets/Header/Header'
import StoreProvider from '../StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TodoNext',
  description: 'Generated by create next app',
}

// const locales = ['en', 'de'];
 
// export function generateStaticParams() {
//   return locales.map((locale) => ({locale}));
// }

 

export default function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (

    
    <html lang={locale}>
      <body className={cl.global}>
        <StoreProvider>
          <Header />
          <main>
            {children}
          </main>
        </StoreProvider>

      </body>
    </html>
  );
}