import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cl from '@/shared/styles/_global.module.scss'
import Header from '@/widgets/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TodoNext',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={cl.global}>
        <Header />
        {children}
      </body>
    </html>
  )
}
